import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Justwravel- Trip Planner",
  description: "Generated by Satnam Singh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
      <body>
        <Navbar/>
        <div className="max-w-[1560px]">{children}  </div>
      </body>
    </html>
  );
}
